/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle;

/**
 *
 * @author chicl
 */
public class FRM_Menu extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Menu
     */
    public FRM_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_base = new javax.swing.JPanel();
        pnl_base2 = new javax.swing.JPanel();
        btn_sair = new javax.swing.JButton();
        btn_receita = new javax.swing.JButton();
        btn_fornecedor = new javax.swing.JButton();
        btn_desenvolv = new javax.swing.JButton();
        btn_cardapio = new javax.swing.JButton();
        btn_produtos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_adms = new javax.swing.JButton();
        Btn_telefone = new javax.swing.JButton();
        lbl_fundinho = new javax.swing.JLabel();
        lbl_fundo = new javax.swing.JLabel();
        lbl_tela = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mni_fornecedor = new javax.swing.JMenuItem();
        mni_telefone = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mni_produtos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mni_receitas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mni_carda = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mni_desenvolv = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mni_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Restaurante");
        setResizable(false);

        pnl_base.setLayout(null);

        pnl_base2.setEnabled(false);
        pnl_base2.setFocusable(false);
        pnl_base2.setOpaque(false);
        pnl_base2.setPreferredSize(new java.awt.Dimension(1031, 819));
        pnl_base2.setRequestFocusEnabled(false);
        pnl_base2.setLayout(null);
        pnl_base.add(pnl_base2);
        pnl_base2.setBounds(0, 0, 1030, 810);

        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(204, 0, 51));
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/exit.png"))); // NOI18N
        btn_sair.setBorderPainted(false);
        btn_sair.setContentAreaFilled(false);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        pnl_base.add(btn_sair);
        btn_sair.setBounds(470, 660, 70, 70);

        btn_receita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_receita.setForeground(new java.awt.Color(204, 0, 51));
        btn_receita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/cozinhando.png"))); // NOI18N
        btn_receita.setBorderPainted(false);
        btn_receita.setContentAreaFilled(false);
        btn_receita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receitaActionPerformed(evt);
            }
        });
        pnl_base.add(btn_receita);
        btn_receita.setBounds(720, 170, 130, 130);

        btn_fornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_fornecedor.setForeground(new java.awt.Color(204, 0, 51));
        btn_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/delivery (1).png"))); // NOI18N
        btn_fornecedor.setBorderPainted(false);
        btn_fornecedor.setContentAreaFilled(false);
        btn_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fornecedorActionPerformed(evt);
            }
        });
        pnl_base.add(btn_fornecedor);
        btn_fornecedor.setBounds(160, 180, 140, 130);

        btn_desenvolv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desenvolv.setForeground(new java.awt.Color(204, 0, 51));
        btn_desenvolv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/icons8-programação-100.png"))); // NOI18N
        btn_desenvolv.setBorderPainted(false);
        btn_desenvolv.setContentAreaFilled(false);
        btn_desenvolv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desenvolvActionPerformed(evt);
            }
        });
        pnl_base.add(btn_desenvolv);
        btn_desenvolv.setBounds(160, 660, 100, 70);

        btn_cardapio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cardapio.setForeground(new java.awt.Color(204, 0, 51));
        btn_cardapio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/cardapio-do-restaurante.png"))); // NOI18N
        btn_cardapio.setBorderPainted(false);
        btn_cardapio.setContentAreaFilled(false);
        btn_cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cardapioActionPerformed(evt);
            }
        });
        pnl_base.add(btn_cardapio);
        btn_cardapio.setBounds(710, 460, 130, 130);

        btn_produtos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_produtos.setForeground(new java.awt.Color(204, 0, 51));
        btn_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/dairy-products (1).png"))); // NOI18N
        btn_produtos.setBorderPainted(false);
        btn_produtos.setContentAreaFilled(false);
        btn_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produtosActionPerformed(evt);
            }
        });
        pnl_base.add(btn_produtos);
        btn_produtos.setBounds(440, 460, 130, 130);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Menu");
        pnl_base.add(jLabel9);
        jLabel9.setBounds(440, 50, 140, 40);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Sair");
        pnl_base.add(jLabel8);
        jLabel8.setBounds(490, 730, 30, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Administradores");
        pnl_base.add(jLabel7);
        jLabel7.setBounds(720, 730, 130, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Cardápio");
        pnl_base.add(jLabel6);
        jLabel6.setBounds(730, 600, 100, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Produtos");
        pnl_base.add(jLabel5);
        jLabel5.setBounds(460, 600, 92, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Fornecedores");
        pnl_base.add(jLabel3);
        jLabel3.setBounds(160, 310, 137, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Telefones");
        pnl_base.add(jLabel12);
        jLabel12.setBounds(160, 600, 100, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Receitas");
        pnl_base.add(jLabel1);
        jLabel1.setBounds(740, 310, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/logo(1).png"))); // NOI18N
        pnl_base.add(jLabel4);
        jLabel4.setBounds(380, 120, 260, 300);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Desenvolvedores");
        pnl_base.add(jLabel10);
        jLabel10.setBounds(140, 730, 140, 30);

        btn_adms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_adms.setForeground(new java.awt.Color(204, 0, 51));
        btn_adms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/menina.png"))); // NOI18N
        btn_adms.setBorderPainted(false);
        btn_adms.setContentAreaFilled(false);
        btn_adms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admsActionPerformed(evt);
            }
        });
        pnl_base.add(btn_adms);
        btn_adms.setBounds(750, 660, 70, 70);

        Btn_telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/telefone.png"))); // NOI18N
        Btn_telefone.setBorderPainted(false);
        Btn_telefone.setContentAreaFilled(false);
        Btn_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_telefoneActionPerformed(evt);
            }
        });
        pnl_base.add(Btn_telefone);
        Btn_telefone.setBounds(130, 460, 160, 137);

        lbl_fundinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/fundoamarelo (1).png"))); // NOI18N
        pnl_base.add(lbl_fundinho);
        lbl_fundinho.setBounds(100, 20, 810, 760);

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/imgfundo(r).jpg"))); // NOI18N
        pnl_base.add(lbl_fundo);
        lbl_fundo.setBounds(0, 0, 2000, 800);
        pnl_base.add(lbl_tela);
        lbl_tela.setBounds(0, 0, 850, 620);

        jMenuBar1.setBackground(new java.awt.Color(204, 0, 0));
        jMenuBar1.setBorder(null);

        jMenu1.setText("Fornecedores");

        mni_fornecedor.setText("Fornecedores");
        mni_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_fornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(mni_fornecedor);

        mni_telefone.setText("Telefones");
        mni_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_telefoneActionPerformed(evt);
            }
        });
        jMenu1.add(mni_telefone);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produtos");

        mni_produtos.setText("Produtos");
        mni_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_produtosActionPerformed(evt);
            }
        });
        jMenu2.add(mni_produtos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Receitas");

        mni_receitas.setText("Receitas");
        mni_receitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_receitasActionPerformed(evt);
            }
        });
        jMenu3.add(mni_receitas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cardápio");

        mni_carda.setText("Cardápio");
        mni_carda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_cardaActionPerformed(evt);
            }
        });
        jMenu4.add(mni_carda);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Desenvolvedores");

        mni_desenvolv.setText("Desenvolvedores");
        mni_desenvolv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_desenvolvActionPerformed(evt);
            }
        });
        jMenu5.add(mni_desenvolv);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Administradores");

        jMenuItem1.setText("Administradores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Sair");

        mni_sair.setText("Sair");
        mni_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_sairActionPerformed(evt);
            }
        });
        jMenu6.add(mni_sair);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mni_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_fornecedorActionPerformed
        frmFornecedor__1 frm = new frmFornecedor__1();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_mni_fornecedorActionPerformed

    private void mni_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_produtosActionPerformed
        frmProduto frm = new frmProduto();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_mni_produtosActionPerformed

    private void mni_receitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_receitasActionPerformed
        frmIngredientes frm = new frmIngredientes();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_mni_receitasActionPerformed

    private void mni_cardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_cardaActionPerformed
       frmCard frm = new frmCard();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_mni_cardaActionPerformed

    private void mni_desenvolvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_desenvolvActionPerformed
        frmDesenvolvedor_ frm = new frmDesenvolvedor_();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_mni_desenvolvActionPerformed

    private void mni_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mni_sairActionPerformed

    private void mni_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_telefoneActionPerformed
        frmTelefone frm = new frmTelefone();
        frm.setVisible(true);
        pnl_base2.add(frm);
    }//GEN-LAST:event_mni_telefoneActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmAdm frm = new frmAdm();
        frm.setVisible(true);
        pnl_base2.add(frm);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_receitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receitaActionPerformed
        frmIngredientes frm = new frmIngredientes();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_btn_receitaActionPerformed

    private void btn_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fornecedorActionPerformed
        frmFornecedor__1 frm = new frmFornecedor__1();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_btn_fornecedorActionPerformed

    private void btn_desenvolvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desenvolvActionPerformed
        frmDesenvolvedor_ frm = new frmDesenvolvedor_();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_btn_desenvolvActionPerformed

    private void btn_cardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cardapioActionPerformed
        frmCard frm = new frmCard();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_btn_cardapioActionPerformed

    private void btn_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produtosActionPerformed
        frmProduto frm = new frmProduto();
        frm.setVisible(true);
        pnl_base2.add( frm );
    }//GEN-LAST:event_btn_produtosActionPerformed

    private void btn_admsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admsActionPerformed
        frmAdm frm = new frmAdm();
        frm.setVisible(true);
        pnl_base2.add(frm);
    }//GEN-LAST:event_btn_admsActionPerformed

    private void Btn_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_telefoneActionPerformed
        // Ação do Botão Destino 1 - Menu Bar
        frmTelefone frm = new frmTelefone();
        frm.setVisible(true);
        pnl_base2.add(frm);
    }//GEN-LAST:event_Btn_telefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_telefone;
    private javax.swing.JButton btn_adms;
    private javax.swing.JButton btn_cardapio;
    private javax.swing.JButton btn_desenvolv;
    private javax.swing.JButton btn_fornecedor;
    private javax.swing.JButton btn_produtos;
    private javax.swing.JButton btn_receita;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_fundinho;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_tela;
    private javax.swing.JMenuItem mni_carda;
    private javax.swing.JMenuItem mni_desenvolv;
    private javax.swing.JMenuItem mni_fornecedor;
    private javax.swing.JMenuItem mni_produtos;
    private javax.swing.JMenuItem mni_receitas;
    private javax.swing.JMenuItem mni_sair;
    private javax.swing.JMenuItem mni_telefone;
    private javax.swing.JPanel pnl_base;
    private javax.swing.JPanel pnl_base2;
    // End of variables declaration//GEN-END:variables
}
